# General
DOCKER_BINDS_DIR=""
DOCKER_COMPOSE_DIR=""
DOCKER_VOL_LOC=""
BACKUP_LOC=""
TS_DOMAIN=""

# Healthchecks
HCHK_SERVER_BACKUP=""
HCHK_SERVER_PING=""
HCHK_PI4_CLONE=""
HCHK_CONTAINER_UPDATE=""
HCHK_PAPERLESS=""
HCHK_IMMICH=""
HCHK_BESZEL=""
HCHK_HEALTHCHECKS=""
HCHK_MEALIE=""
HCHK_OLLAMA=""
HCHK_SEARXNG=""
HCHK_STIRLING=""

# API Keys
APIKY_BESZEL=""
APIKY_MEALIE=""
